#!/usr/bin/env python3
"""Write the handler fan-out from the trait it fans out.

`Wrapper` has ninety calls. Every one of them has to reach the session's own
record and then each handler the caller registered, and a call written by hand
is a call somebody forgets — which is a message a handler is never told about,
silently, for exactly one callback.

Run it, commit what it writes. `scripts/gate.py` re-runs it and fails if what
is committed is not what it produces.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
TRAIT = ROOT / "src/api/wrapper.rs"
OUT = ROOT / "src/api/session/fanout.rs"


def trait_body(text: str) -> str:
    """The trait, and nothing after it.

    Slicing to the last `\n}` in the file ran past the trait into the tests
    below it, so a test function counted as a call to fan out — and the count
    that was supposed to prove the fan-out complete was measuring the wrong
    thing.
    """
    at = text.index("pub trait Wrapper {")
    depth, i = 0, text.index("{", at)
    for j in range(i, len(text)):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return text[at:j]
    raise ValueError("the trait does not close")


def imports(text: str) -> list[str]:
    """The imports the trait's own signatures resolve through.

    Taken from the trait's file rather than listed here: a type added to a
    signature resolves there and would resolve nowhere in what this writes.
    """
    return [line for line in text.splitlines() if line.startswith("use ")]


def declared(text: str) -> set[str]:
    """Every call the trait declares, however its signature is written."""
    return {m.group(1) for m in re.finditer(r"^    fn (\w+)\(", trait_body(text), re.M)}


def calls() -> list[tuple[str, str, list[str]]]:
    """Each call the trait declares: its name, its signature, its argument names."""
    text = TRAIT.read_text()
    body = trait_body(text)
    found = []
    # `&mut self` sits on the next line where a signature is long enough to
    # wrap, and twenty-seven of the ninety are. Matched only when adjacent,
    # those twenty-seven were left out of the fan-out and nothing said so.
    for m in re.finditer(
        r"^    fn (\w+)\(\s*&mut self(?:,\s*)?((?:[^;{]|\n)*?)\)\s*\{", body, re.M
    ):
        name, args = m.group(1), " ".join(m.group(2).split())
        names = []
        depth = 0
        current = ""
        for ch in args:
            if ch in "<([":
                depth += 1
            elif ch in ">)]":
                depth -= 1
            if ch == "," and depth == 0:
                names.append(current)
                current = ""
            else:
                current += ch
        if current.strip():
            names.append(current)
        # `name: Type`, and a name may be `_` where the trait ignores it.
        passed = [a.split(":")[0].strip() for a in names if ":" in a]
        found.append((name, args, passed))
    return found


def main() -> int:
    text = TRAIT.read_text()
    missed = declared(text) - {name for name, _, _ in calls()}
    if missed:
        # A call left out is a message a handler is never told about, silently,
        # for exactly one kind of message. Better to write nothing.
        print("the fan-out would leave out calls the trait declares:")
        for name in sorted(missed):
            print(f"  {name}")
        return 1

    lines = [
        "//! Generated by `scripts/gen_fanout.py`. Do not edit.",
        "//!",
        "//! Every call the session receives reaches its own record of the session",
        "//! and then each handler the caller registered, in the order they were",
        "//! added. Written by hand, a call is a call somebody forgets — and a",
        "//! forgotten one is a message a handler is never told about, silently, for",
        "//! exactly one kind of message.",
        "",
        "#![allow(unused_variables)]",
        "",
        "use super::Fanout;",
        "use crate::api::wrapper::Wrapper;",
        # Whatever the trait's own signatures name. Listed here instead, an
        # argument type added to the trait names nothing in this file.
        *imports(TRAIT.read_text()),
        "",
        "impl Wrapper for Fanout<'_> {",
    ]
    for name, args, passed in calls():
        args = f", {args}" if args else ""
        forward = ", ".join(passed)
        lines += [
            f"    fn {name}(&mut self{args}) {{",
            f"        self.kept.{name}({forward});",
            "        for handler in self.handlers.iter_mut() {",
            f"            handler.{name}({forward});",
            "        }",
            "    }",
        ]
    lines += ["}", ""]
    OUT.write_text("\n".join(lines))
    print(f"{len(calls())} calls fanned out to the session and its handlers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
